# Generated by Django 5.1.6 on 2025-04-22 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDinerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Deliver', to='blogs.blogmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Diner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog diner',
                'verbose_name_plural': 'Blog diners',
            },
        ),
    ]
