# Generated by Django 5.1.6 on 2025-04-22 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogdinermodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sabina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Candy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sabina',
                'verbose_name_plural': 'Sabina',
            },
        ),
    ]
